### ISSUE TITLE
Can't login after register with uppercase username

### ISSUE THREAD

**Issue by antimech** [dogecodes/react-chat-api#4]
https://github.com/dogecodes/react-chat-api/blob/1656fc0666f8203a9d7af3b6eab75d8149de8e08/controllers/auth.js#L58

**Comment by denysdovhan** [comment]
Can you fix this problem?

**Comment by dmitryt** [comment]
@denysdovhan, at first we should answer the question - whether usernames "user" and "UsEr" are supposed to be the same name or not?

**Comment by denysdovhan** [comment]
> whether usernames "user" and "UsEr" are supposed to be the same name or not?

I think we will use the same logic as Twitter for example. They should be the same usernames.

**Comment by antimech** [comment]
https://github.com/dogecodes/react-chat-api/pull/7

**Comment by dmitryt** [comment]
Guys, according to @denysdovhan [comment](https://github.com/dogecodes/react-chat-api/issues/4#issuecomment-391985716) usernames should be case insensitive.
Current fix has removed username's conversion to lower case. So, we've got case sensitive flow.
Just correct me, if I'm wrong.

**Comment by denysdovhan** [comment]
Yes, but anyway it looks good to me.
