### ISSUE TITLE
GET VS POST for Logout

### ISSUE THREAD

**Issue by dmitryt** [dogecodes/react-chat-api#5]
It's just a minor issue, but I think it's better to use POST request for [logout](https://github.com/dogecodes/react-chat-api/blob/master/routes/auth.js#L52), because we're changing the state of our App. However there is no unanimous opinion on the internet about it.

**Comment by antimech** [comment]
+1 for POST

**Comment by denysdovhan** [comment]
Yeah, reasonable for larger apps. But here we don't send anything to the backend.

We could fix that, but let's introduce breaking changes to the application. That may cause problems for other students of DogeCodes course.
